server:
  port: 8080

# actuator port
management:
  server:
    port: 8082
  endpoints:
    web.exposure.include: '*'

spring:
  application:
    name: keeperservice
  profiles:
    active: test
  config:
    import: 'configserver:http://localhost:8888'

  cloud:
    bus:
      enabled: true
    stream:
      kafka.binder:
          zkNodes: localhost:2181
          brokers: localhost:9092

logging:
  level:
    org.springframework.web.client: TRACE

test.key: val
